name: Go test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        go: ["1.16", "1.15", "1.14"]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go environment 1.1x
        uses: actions/checkout@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Report percent test coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
